### ISSUE TITLE
score database

### ISSUE THREAD

**Issue by Oleafeon** [daleharvey/pacman#15]
How can i make it so that the score wil be uploaded to a database, So i can make a highscore page

**Comment by mistajase79** [comment]
Database access can be done using PHP and MySQL (PDO recommended)
I used javascript to create a form at the end of the game (to prevent anyone from changing values mid game) and posted the form to a php script which contained all the logic for DB insertion

**Comment by Oleafeon** [comment]
Alright thanks, i will look into it

**Comment by mandric** [comment]
Maybe use PouchDB to store your scores locally and then sync peer-to-peer or to a centralized location?
